const BYTES_PER_MEGABYTE = 1024 * 1024;

export const IMAGE_MAX_SIZE_MB = 5;
export const IMAGE_MAX_SIZE = IMAGE_MAX_SIZE_MB * BYTES_PER_MEGABYTE;
export const IMAGE_MAX_SIZE_LABEL = `${IMAGE_MAX_SIZE_MB}MB`;
